# -*- coding: utf-8 -*-
"""Q1_ASL_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u18BQ0vKt6VCnnhWQloZGmRMeNE8Z752

<div align=center>
		
<p></p>
<p></p>
<font size=5>
In the Name of God
<font/>
<p></p>
 <br/>
    <br/>
    <br/>
<font color=#FF7500>
Sharif University of Technology - Departmenet of Computer Engineering
</font>
<p></p>
<font color=blue>
Artifical Intelligence - Dr. Mohammad Hossein Rohban
</font>
<br/>
<br/>
Fall 2022

</div>

<hr/>
		<div align=center>
		    <font color=red size=6>
			    <br />
Practical Assignment 3 <br>
American Sign Language Image Classification
            	<br/>
			</font>
    <br/>
    <br/>
<font size=4>
			<br/><br/>
Deadline:  
                <br/><b>
              Cheating is Strongly Prohibited
                </b><br/><br/>
                <font color=red>
Please run all the cells.
     </font>
</font>
<br>
<font size=3 color=grey>
Author: Sayeh Jarollahi
</font>
                <br/>
    </div>
"""

# Set your student number
student_number = 99105775
Name = 'Mehrad'
Last_Name = 'Milanloo'

"""In this question, you will train a neural network for classifying sign language images. The American  Sign Language (ASL) dataset consists of 2515 images from different numbers and alphabets. The images are in RGB format and are not the same size. The dataset is classified into 36 classes (10 numbers and 26 alphabets). 

You will need to train a model to classify this dataset into different categories. You are allowed to use MLP as well as CNN networks. 

**Grading Policy:** For a full mark on this assignment, your notebook should be completely runnable by the TA. Additionally, you must reach an accuracy of %96 on the test data.

It is highly recommended to use google colab and utilize its GPUs. However, if you want to run the notebook locally, you can reach and download the dataset in this [link](https://drive.google.com/file/d/11_4-N8EdtoLPiW3YyJ840CXM0FckO1e5/view?usp=share_link).

## Setup
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/'Colab Notebooks'/ASL_Classification
# %pwd

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.image import imread
import cv2
import random
import os

from PIL import Image
from sklearn.model_selection import train_test_split
from IPython.display import clear_output

import torch
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader, random_split
from torch import nn
from q1_helper_code import get_files

#########################################
#                                       #
#  import other necessery packages here #
#                                       #
#########################################

# NOTE: It is highly recommended to use colab GPUs!
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

"""## Download and unzip the dataset

"""

#! wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=11_4-N8EdtoLPiW3YyJ840CXM0FckO1e5' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=11_4-N8EdtoLPiW3YyJ840CXM0FckO1e5" -O asl_dataset.zip && rm -rf /tmp/cookies.txt
#! unzip asl_dataset.zip

main_dir = "asl_dataset/asl_dataset"
class_dirs = os.listdir(main_dir)

"""## Transform 

Data transformation is the process of converting data from one format or structure into another format or structure. Transformers change pixel values but still keep almost the whole information of the image.[source](https://towardsdatascience.com/improves-cnn-performance-by-applying-data-transformation-bf86b3f4cef4) You can read more about them in the mentioned source. 

You are going to implement two different transformers from scratch. These transformers will be used once the data is loaded.

### Resize 
This transformer recieves a tensor (3\*x\*y) and returns a tensor with shape (3\*size\*size)
"""

class Resize(object):
    
    def __init__(self, size=50):
        self.output_size = (size, size)
        pass
    #############################
    #       Code here           #
    #############################
  
    def __call__(self, x):
        '''
        This function recieves a tensor and applies the resizing on that and returns that tensor
        '''
        new_h, new_w = self.output_size
        new_h, new_w = int(new_h), int(new_w)
        r = transforms.Resize(new_h)
        x = r(x)
        return x

    #############################
    #       Code here           #
    #############################
        return x

"""### GrayScale
This transform is helpful to decrease the number of channels, so the training gets faster. 

Feel free to add args to functions or change them if you need to!
"""

class GrayScale(object):

    def __init__(self):
    #############################
    #       Code here           #
    #############################
        pass

    def __call__(self, img):
    #############################
    #       Code here           #
    #############################
        x = transforms.Grayscale()
        img_gray = x(img)
        return img_gray

"""## Load Data and compose transforms 
You can combine Transforms using the **compose** method in the torchvision.transforms library.
"""

# Ddd the implemented transforms
###
# NOTE: You can add more transforms if you want
###
transform = transforms.Compose([
    Resize(),
    GrayScale(),
    transforms.ToTensor()
])
    #############################
    #         Code here         #
    #############################

"""Plot one random sample from each class of the datset:"""

'''
Hint:
Get two random samples from files in each directory and use subplot to add those
images to the plot. 
Use previously defined transform to test your transforms
'''
plt.figure(figsize=(11,11))
for i, directory in enumerate(class_dirs):
    files_name = os.listdir(f"{main_dir}/{directory}")
    random_files = random.sample(files_name, 2)
    for j, file in enumerate(random_files):
        img = Image.open(f"{main_dir}/{directory}/{file}")
        img = transform(img)
        plt.subplot(len(class_dirs), 2, 2*i+j+1)
        plt.imshow(img.squeeze(), cmap='gray')
        plt.title(f"{directory}")
        plt.axis('off')
plt.show()

    #############################
    #         Code here         #
    #############################

"""## Create Dataset 
Code for processing data samples can get messy and hard to maintain; we ideally want our dataset code to be decoupled from our model training code for better readability and modularity. [from [Pytorch Documentation](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html)] 

In this section, you will implement a custom dataset which gets address of files and loads them as needed. 
"""

def get_lab(s):
  if s.isnumeric():
    return int(s)
  return ord(s) - ord('a') + 10

class ASLDataset(Dataset):
    def __init__(self, files_address:list, transform=transform):
        #############################
        #         Code here         #
        #############################
        self.files_address = files_address
        self.transform = transform
        pass

    def __len__(self):
        # returns length of the data

        #############################
        #         Code here         #
        #############################
        return len(self.files_address)

    def __getitem__(self, idx):
        # Hint: load image from files_address and the label from name of the directory 
        # Remember to apply transforms!
        image = Image.open(self.files_address[idx])
        image = self.transform(image)
        label = self.files_address[idx].split('/')[-2]
        # label = pd.Categorical(pd.factorize(label)[0])[0]
        #############################
        #         Code here         #
        #############################
        return image, get_lab(label)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/'Colab Notebooks'/ASL_Classification
# %pwd

files_addr, labels = get_files()
print(len(labels), len(files_addr))

"""## Create Datasets  

First split data to train, validation and test using the `train_test_split funciton`. Remember to shuffle data. Then create ASLDataset for each part of data. 
"""

#############################
#         Code here         #
#############################
x_train, x_test, y_train, y_test = train_test_split(files_addr, labels, test_size=0.2, random_state=42, shuffle=True)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42, shuffle=True)
train_dataset = ASLDataset(x_train)
val_dataset = ASLDataset(x_val)
test_dataset = ASLDataset(x_test)

"""Use datasets to create DataLoader from `torch.utils.DataLoader` class

Note: You should make `shuffle=True` for the training dataLoader, so in each epoch the data reshuffles. 
"""

num_threads = 2

#############################
#         Code here         #
#############################
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

"""## Define Model """

class ASLModel(nn.Module):
    def __init__(self, in_channels, num_classes):
        super().__init__()
        self.network = nn.Sequential(
            nn.Conv2d(in_channels, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Flatten(),
            nn.Linear(64*12*12, 256),
            nn.ReLU(),
            nn.Linear(256, num_classes)
        )
            #############################
            #         Code here         #
            ############################# 
        self.init_weights(self.network)
        
    def init_weights(self, m):
        if type(m) == nn.Linear or type(m) == nn.Conv2d:
            nn.init.xavier_uniform_(m.weight)
            m.bias.data.fill_(0.01)

    def weights_init(self):
        self.network.apply(self.init_weights)

    def forward(self, xb):
        return self.network(xb)
        #############################
        #         Code here         #
        #############################
        pass

in_channels = 1
num_classes = 36
model = ASLModel(in_channels, num_classes).to(device)
print(sum(p.numel() for p in model.parameters()))

"""## Define optimizer, Criterion and other parameters 

"""

#############################
#         Code here         #
#############################
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-5)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=5)
loss = None

# Set parameters and hyper parameters
num_epochs = 30
batch_size = 32
learning_rate = 0.001
input_size = 3

best_model = None
best_acc = 0

def train_val (model, trainloader, val_loader, f_loss, optimizer, n_epochs, device = device):
    train_loss_arr, val_loss_arr = [], []
    train_acc_arr, val_acc_arr = [], []  
    for epoch in range(n_epochs):
        train_loss, val_loss = 0, 0
        model.train()
        train_acc, val_acc = 0, 0
        for batch_idx, (data, target) in enumerate(trainloader):
            data, target = data.to(device), torch.tensor(target).to(device)
            optimizer.zero_grad()
            batch_size = data.size(0)
            output = model(data)
            batch_loss = f_loss(output, target)
            batch_loss.backward()
            optimizer.step()
            train_loss += batch_loss * batch_size
            _, predicted = torch.max(output.data, 1)
            train_acc += (predicted == target).sum().item()
        train_loss /= len(trainloader.dataset)
        train_acc /= len(trainloader.dataset)
        train_loss_arr.append(train_loss)
        train_acc_arr.append(train_acc)

        #############################
        #         Code here         #
        #############################
        ## Hint: Loop throught train_loader, get images with their labels and train the model
        ## Hint 2: To update train_loss inside the loop use "train_loss += batch_loss * batch_size""
        ## Hint 3: To update train_acc get the predicted label of each training data and compare with the real label
                
        model.eval()
        with torch.no_grad():
            for batch_idx, (data, target) in enumerate(val_loader):
                data, target = data.to(device), torch.tensor(target).to(device)
                batch_size = data.size(0)
                output = model(data)
                batch_loss = f_loss(output, target)
                val_loss += batch_loss * batch_size
                _, predicted = torch.max(output.data, 1)
                val_acc += (predicted == target).sum().item()
        val_loss /= len(val_loader.dataset)
        val_acc /= len(val_loader.dataset)
        val_loss_arr.append(val_loss)
        val_acc_arr.append(val_acc)
        scheduler.step(val_loss)

        #############################
        #         Code here         #
        #############################
        ## Hint: Loop throught val_loader, get images with their labels and evaluate the model
        ## Hint 2: To update val_loss inside the loop use "val_loss += batch_loss * batch_size""
        ## Hint 3: you have to keep the best model in the best_model variable to use it in the testing phase
        ## Hint 4: you have to keep the best accuracy in the best_acc variable to use it in the testing phase
        global best_acc, best_model
        if val_acc > best_acc:
            best_acc = val_acc
            best_model = model.state_dict()
        ####
        #############################
        #         Code here         #
        #############################
        # append accuracy of train and valid to the lists
        # append loss of train and valid to the lists


        print(f"[Epoch {epoch}]\t"
            f"Train Loss: {train_loss:.4f}\t"
            f"Validation Loss: {val_loss:.4f}\t", f'train acc {train_acc}\t' + f'validation acc {val_acc}')
    return train_loss_arr, val_loss_arr, train_acc_arr, val_acc_arr

# Call the train_val function
train_loss_arr, val_loss_arr, train_acc_arr, val_acc_arr = train_val(model, train_loader, val_loader, criterion, optimizer, num_epochs)

"""## Plot loss and accuracy

You must have one plot for loss according to epoch for train/val.

Also, another plot for accuracy according to epoch for train/val
"""

plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.plot(torch.tensor(train_loss_arr).cpu().detach().numpy(), label='Train')
plt.plot(torch.tensor(val_loss_arr).cpu().detach().numpy(), label='Validation')
plt.legend()
plt.title('Loss')
plt.subplot(1, 2, 2)
plt.plot(train_acc_arr, label='Train')
plt.plot(val_acc_arr, label='Validation')
plt.legend()
plt.title('Accuracy')
plt.show()
#############################
#         Code here         #
#############################

"""## Evaluate model on the test dataset

Evaluate your best model on the test dataset. You should get accuracy above ***%96*** for a full-mark.

Remember to print the accuracy of model on the test dataset! 
"""

#############################
#         Code here         #
#############################
f_loss = criterion
model.load_state_dict(best_model)
test_loss, test_acc = 0, 0
model.eval()
with torch.no_grad():
    for batch_idx, (data, target) in enumerate(test_loader):
        data, target = data.to(device), torch.tensor(target).to(device)
        batch_size = data.size(0)
        output = model(data)
        batch_loss = f_loss(output, target)
        test_loss += batch_loss * batch_size
        _, predicted = torch.max(output.data, 1)
        test_acc += (predicted == target).sum().item()
test_loss /= len(test_loader.dataset)
test_acc /= len(test_loader.dataset)
print(test_loss.item(), test_acc)